export const limits = {
	maxMainCategoriesPerKind: 100,
	maxSubcategoriesPerParent: 100,
	budgetWarningPercent: 80,
	budgetOverPercent: 100,
	fxCronMaxAttempts: 3,
	systemBaseCurrency: 'USD',
	importMaxRows: 100,
	importDescriptionMaxLength: 500,
	exportMaxRangeDays: 730,
	defaultTimezone: 'UTC',
	reviewMinTransactions: 5,
	reviewMinExpenseCount: 3,
	reviewComparisonMonths: 2,
	reviewUiRecentCount: 3,
	insightsMaxInputChars: 12_000,
	listDefaultPageSize: 20,
	listMaxPageSize: 100,
	suggestDescriptionsLimit: 3,
	dashboardRecentTransactions: 8,
	dashboardCategoryTopN: 6,
	trendsMaxCategoryIds: 2,
	avatarUploadMaxBytes: 10 * 1024 * 1024,
	avatarSizePx: 160,
	avatarWebpQuality: 80,
	avatarBlobFolder: 'fintrack-user-avatar',
} as const;

export type Limits = typeof limits;
